-- MySQL Script generated by MySQL Workbench
-- Mon Nov  1 14:49:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_1` ;

-- -----------------------------------------------------
-- Schema db_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_1` DEFAULT CHARACTER SET utf8 ;
USE `db_1` ;

-- -----------------------------------------------------
-- Table `db_1`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_1`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `db_1`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `num_registro` INT NULL,
  `email_usuario` VARCHAR(30) NULL,
  `password` VARCHAR(300) NULL,
  `nombre` VARCHAR(15) NULL,
  `primer_apellido` VARCHAR(10) NULL,
  `segundo_apellido` VARCHAR(10) NULL,
  `imagen_usuario` BLOB NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `num_registro_UNIQUE` (`num_registro` ASC) VISIBLE,
  UNIQUE INDEX `email_usuario_UNIQUE` (`email_usuario` ASC) VISIBLE,
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_1`.`vigencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_1`.`vigencia` ;

CREATE TABLE IF NOT EXISTS `db_1`.`vigencia` (
  `id_vigencia` INT NOT NULL AUTO_INCREMENT,
  `expedicion` DATETIME NULL,
  `vencimiento` DATETIME NULL,
  `resp_grupo` INT,
  PRIMARY KEY (`id_vigencia`),
  UNIQUE INDEX `id_vigencia_UNIQUE` (`id_vigencia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_1`.`tipo_tramite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_1`.`tipo_tramite` ;

CREATE TABLE IF NOT EXISTS `db_1`.`tipo_tramite` (
  `id_tipo_tramite` INT NOT NULL AUTO_INCREMENT,
  `manifestacion` VARCHAR(12) NULL,
  `licencia` VARCHAR(85) NULL,
  `otra_resp` VARCHAR(30) NULL,
  `resp_grupo` INT,
  PRIMARY KEY (`id_tipo_tramite`),
  UNIQUE INDEX `id_tipo_tramite_UNIQUE` (`id_tipo_tramite` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_1`.`propietario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_1`.`propietario` ;

CREATE TABLE IF NOT EXISTS `db_1`.`propietario` (
  `id_propietario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NULL,
  `primer_apellido` VARCHAR(10) NULL,
  `segundo_apellido` VARCHAR(10) NULL,
  `telefono` VARCHAR(10) NULL,
  `rfc` VARCHAR(13) NULL,
  `resp_grupo` INT,
  PRIMARY KEY (`id_propietario`),
  UNIQUE INDEX `rfc_UNIQUE` (`rfc` ASC) VISIBLE,
  UNIQUE INDEX `id_propietario_UNIQUE` (`id_propietario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_1`.`predio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_1`.`predio` ;

CREATE TABLE IF NOT EXISTS `db_1`.`predio` (
  `id_predio` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NULL,
  `num_interior` VARCHAR(30) NULL,
  `num_exterior` VARCHAR(30) NULL,
  `superficie_predio` VARCHAR(10) NULL,
  `niveles_snb` INT NULL,
  `niveles_bnb` INT NULL,
  `colonia` VARCHAR(30) NULL,
  `alcaldia` VARCHAR(20) NULL,
  `cp` INT NULL,
  `viviendas` INT NULL,
  `cajones` INT NULL,
  `altura_soporte` VARCHAR(45) NULL,
  `antenas` INT NULL,
  `longitud_instalacion_subt` VARCHAR(45) NULL,
  `resp_grupo` INT,
  `id_propietario` INT NOT NULL,
  PRIMARY KEY (`id_predio`),
  INDEX `fk_predio_propietario1_idx` (`id_propietario` ASC) VISIBLE,
  UNIQUE INDEX `id_predio_UNIQUE` (`id_predio` ASC) VISIBLE,
  CONSTRAINT `fk_predio_propietario1`
    FOREIGN KEY (`id_propietario`)
    REFERENCES `db_1`.`propietario` (`id_propietario`)
    ON DELETE CASCADE ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_1`.`observaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_1`.`observaciones` ;

CREATE TABLE IF NOT EXISTS `db_1`.`observaciones` (
  `id_observaciones` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  `resp_grupo` INT,
  `id_tipo_tramite` INT NOT NULL,
  PRIMARY KEY (`id_observaciones`),
  INDEX `fk_observaciones_tipo_tramite1_idx` (`id_tipo_tramite` ASC) VISIBLE,
  UNIQUE INDEX `id_observaciones_UNIQUE` (`id_observaciones` ASC) VISIBLE,
  CONSTRAINT `fk_observaciones_tipo_tramite1`
    FOREIGN KEY (`id_tipo_tramite`)
    REFERENCES `db_1`.`tipo_tramite` (`id_tipo_tramite`)
    ON DELETE CASCADE ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_1`.`responsiva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_1`.`responsiva` ;

CREATE TABLE IF NOT EXISTS `db_1`.`responsiva` (
  `id_responsiva` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `folio` VARCHAR(10) NULL,
  `superficie_responsiva` VARCHAR(10) NULL,
  `num_catastral` VARCHAR(15) NULL,
  `uso` VARCHAR(100) NULL,
  `area_patrimonial` VARCHAR(10) NULL,
  `uso_de_suelo` VARCHAR(15) NULL,
  `index_col` INT NULL,
  `periodo` INT NULL,
  `resp_grupo` INT,
  `id_usuario` INT NOT NULL,
  `id_vigencia` INT NOT NULL,
  `id_tipo_tramite` INT NOT NULL,
  `id_predio` INT NOT NULL,
  `id_observaciones` INT NOT NULL,
  PRIMARY KEY (`id_responsiva`),
  INDEX `fk_responsiva_vigencia1_idx` (`id_vigencia` ASC) VISIBLE,
  INDEX `fk_responsiva_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_responsiva_tipo_tramite1_idx` (`id_tipo_tramite` ASC) VISIBLE,
  INDEX `fk_responsiva_predio1_idx` (`id_predio` ASC) VISIBLE,
  INDEX `fk_responsiva_observaciones1_idx` (`id_observaciones` ASC) VISIBLE,
  UNIQUE INDEX `id_responsiva_UNIQUE` (`id_responsiva` ASC) VISIBLE,
  CONSTRAINT `fk_responsiva_vigencia1`
    FOREIGN KEY (`id_vigencia`)
    REFERENCES `db_1`.`vigencia` (`id_vigencia`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_responsiva_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_1`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_responsiva_tipo_tramite1`
    FOREIGN KEY (`id_tipo_tramite`)
    REFERENCES `db_1`.`tipo_tramite` (`id_tipo_tramite`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_responsiva_predio1`
    FOREIGN KEY (`id_predio`)
    REFERENCES `db_1`.`predio` (`id_predio`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_responsiva_observaciones1`
    FOREIGN KEY (`id_observaciones`)
    REFERENCES `db_1`.`observaciones` (`id_observaciones`)
    ON DELETE CASCADE ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

